import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import styles from "./style.module.scss";
import Link from "next/link";
import { Nav } from "@/components";
import Image from "next/image";
import React from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Learning Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>
        <div className={styles.container}>
          <Link href="/">
            <Image
              src="/images/logo.svg"
              alt="Home"
              width={100}
              height={50}
              layout={"blur-up"}
              objectFit={"cover"}
            />
          </Link>
          <Nav />
          {children}
        </div>
      </body>
    </html>
  );
}
